// <auto-generated />
using System;
using EF_MSSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_MSSQL.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20260407072656_DataSeeder")]
    partial class DataSeeder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsMember")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Entities.CustomerContactInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("CustomerContactInfo");
                });

            modelBuilder.Entity("Entities.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("NewPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PaymentMethodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShippingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("ShippingId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Entities.PaymentMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PaymentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QtyInStock")
                        .HasColumnType("int");

                    b.Property<Guid>("SubCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000000"),
                            Description = "Pålitlig vardagslaptop med Intel Core i5 och 16GB RAM.",
                            Name = "Acer Aspire 15\"",
                            Price = 7995m,
                            QtyInStock = 18,
                            SubCategoryId = new Guid("00000101-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000002-0000-0000-0000-000000000000"),
                            Description = "Affärslaptop med robust byggkvalitet och lång batteritid.",
                            Name = "Lenovo ThinkPad E14",
                            Price = 9495m,
                            QtyInStock = 12,
                            SubCategoryId = new Guid("00000101-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000003-0000-0000-0000-000000000000"),
                            Description = "Kompakt och lättviktig laptop för studenter.",
                            Name = "ASUS VivoBook 14\"",
                            Price = 6495m,
                            QtyInStock = 22,
                            SubCategoryId = new Guid("00000101-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000004-0000-0000-0000-000000000000"),
                            Description = "Premium laptop med OLED-skärm och Intel Core i7.",
                            Name = "Dell XPS 15\"",
                            Price = 16995m,
                            QtyInStock = 7,
                            SubCategoryId = new Guid("00000101-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000005-0000-0000-0000-000000000000"),
                            Description = "Konvertibel 2-i-1 laptop med pekskärm och stylus.",
                            Name = "HP Spectre x360 14\"",
                            Price = 14495m,
                            QtyInStock = 9,
                            SubCategoryId = new Guid("00000101-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000006-0000-0000-0000-000000000000"),
                            Description = "Kompakt stationär dator med Intel Core i5 och 512GB SSD.",
                            Name = "HP Pavilion Desktop",
                            Price = 8995m,
                            QtyInStock = 10,
                            SubCategoryId = new Guid("00000102-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000007-0000-0000-0000-000000000000"),
                            Description = "Affärsdator med hög prestanda och energieffektivitet.",
                            Name = "Dell OptiPlex 7000",
                            Price = 11495m,
                            QtyInStock = 6,
                            SubCategoryId = new Guid("00000102-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000008-0000-0000-0000-000000000000"),
                            Description = "Stilren stationär dator för hem och kontor.",
                            Name = "Lenovo IdeaCentre 5",
                            Price = 7495m,
                            QtyInStock = 14,
                            SubCategoryId = new Guid("00000102-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000009-0000-0000-0000-000000000000"),
                            Description = "Kraftfull gaming-desktop med RTX 4070 och 32GB RAM.",
                            Name = "ASUS ROG Strix G15",
                            Price = 19995m,
                            QtyInStock = 5,
                            SubCategoryId = new Guid("00000102-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000010-0000-0000-0000-000000000000"),
                            Description = "27-tums QHD-skärm med 165Hz och 1ms responstid.",
                            Name = "MSI MAG 27\" QHD",
                            Price = 4295m,
                            QtyInStock = 15,
                            SubCategoryId = new Guid("00000103-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000011-0000-0000-0000-000000000000"),
                            Description = "Ultravid 34-tums skärm med IPS-panel och USB-C.",
                            Name = "LG UltraWide 34\"",
                            Price = 5995m,
                            QtyInStock = 9,
                            SubCategoryId = new Guid("00000103-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000012-0000-0000-0000-000000000000"),
                            Description = "Professionell 4K-skärm med exceptionell färgåtergivning.",
                            Name = "Dell UltraSharp 27\" 4K",
                            Price = 7495m,
                            QtyInStock = 8,
                            SubCategoryId = new Guid("00000103-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000013-0000-0000-0000-000000000000"),
                            Description = "Böjd VA-skärm med 144Hz för en uppslukande upplevelse.",
                            Name = "Samsung 32\" Curved",
                            Price = 3795m,
                            QtyInStock = 11,
                            SubCategoryId = new Guid("00000103-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000014-0000-0000-0000-000000000000"),
                            Description = "Trådlöst tangentbord med bakgrundsbelysning och multienhetspar.",
                            Name = "Logitech MX Keys",
                            Price = 1195m,
                            QtyInStock = 25,
                            SubCategoryId = new Guid("00000104-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000015-0000-0000-0000-000000000000"),
                            Description = "Ergonomisk trådlös mus med precision scroll och tyst klick.",
                            Name = "Logitech MX Master 3S",
                            Price = 995m,
                            QtyInStock = 30,
                            SubCategoryId = new Guid("00000104-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000016-0000-0000-0000-000000000000"),
                            Description = "15-knappars LCD-kontroller för streamers och kreatörer.",
                            Name = "Elgato Stream Deck MK.2",
                            Price = 1595m,
                            QtyInStock = 12,
                            SubCategoryId = new Guid("00000104-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000017-0000-0000-0000-000000000000"),
                            Description = "Flaggskepp med AI-funktioner, 50MP kamera och 120Hz AMOLED.",
                            Name = "Samsung Galaxy S24",
                            Price = 9995m,
                            QtyInStock = 25,
                            SubCategoryId = new Guid("00000201-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000018-0000-0000-0000-000000000000"),
                            Description = "Apple iPhone 15 med Dynamic Island och USB-C.",
                            Name = "iPhone 15",
                            Price = 11995m,
                            QtyInStock = 20,
                            SubCategoryId = new Guid("00000201-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000019-0000-0000-0000-000000000000"),
                            Description = "Ren Android-upplevelse med exceptionell kameramjukvara.",
                            Name = "Google Pixel 8",
                            Price = 8495m,
                            QtyInStock = 14,
                            SubCategoryId = new Guid("00000201-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000020-0000-0000-0000-000000000000"),
                            Description = "Mellanklass med premiumkänsla, 5G och 50MP kamera.",
                            Name = "Samsung Galaxy A55",
                            Price = 4995m,
                            QtyInStock = 30,
                            SubCategoryId = new Guid("00000201-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000021-0000-0000-0000-000000000000"),
                            Description = "Snabb laddning 100W, Snapdragon 8 Gen 3 och Hasselblad-kamera.",
                            Name = "OnePlus 12",
                            Price = 8995m,
                            QtyInStock = 16,
                            SubCategoryId = new Guid("00000201-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000022-0000-0000-0000-000000000000"),
                            Description = "Allsidig surfplatta med A14 Bionic och USB-C.",
                            Name = "iPad 10:e gen",
                            Price = 5495m,
                            QtyInStock = 18,
                            SubCategoryId = new Guid("00000202-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000023-0000-0000-0000-000000000000"),
                            Description = "Android-surfplatta med AMOLED-skärm och S Pen.",
                            Name = "Samsung Galaxy Tab S9",
                            Price = 7995m,
                            QtyInStock = 11,
                            SubCategoryId = new Guid("00000202-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000024-0000-0000-0000-000000000000"),
                            Description = "12.6-tums AMOLED-surfplatta med Snapdragon 870.",
                            Name = "Lenovo Tab P12 Pro",
                            Price = 6495m,
                            QtyInStock = 9,
                            SubCategoryId = new Guid("00000202-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000025-0000-0000-0000-000000000000"),
                            Description = "Stöttåligt skal med Air Cushion Technology.",
                            Name = "Spigen Tough Armor iPhone 15",
                            Price = 299m,
                            QtyInStock = 80,
                            SubCategoryId = new Guid("00000203-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000026-0000-0000-0000-000000000000"),
                            Description = "Kompakt GaN-laddare med 65W och stöd för tre enheter.",
                            Name = "Anker USB-C Snabbladdare 65W",
                            Price = 449m,
                            QtyInStock = 60,
                            SubCategoryId = new Guid("00000203-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000027-0000-0000-0000-000000000000"),
                            Description = "Magnetiskt skal med inbyggd plånbok för iPhone 15.",
                            Name = "Belkin MagSafe Plånboksskal",
                            Price = 399m,
                            QtyInStock = 45,
                            SubCategoryId = new Guid("00000203-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000028-0000-0000-0000-000000000000"),
                            Description = "QLED med Quantum HDR och 120Hz för sport och gaming.",
                            Name = "Samsung 65\" QLED 4K",
                            Price = 14995m,
                            QtyInStock = 8,
                            SubCategoryId = new Guid("00000301-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000029-0000-0000-0000-000000000000"),
                            Description = "Prisbelönt OLED-TV med perfekta svärtor och Dolby Vision.",
                            Name = "LG OLED 55\" C3",
                            Price = 17995m,
                            QtyInStock = 5,
                            SubCategoryId = new Guid("00000301-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000030-0000-0000-0000-000000000000"),
                            Description = "Google TV med Cognitive Processor XR och Dolby Atmos.",
                            Name = "Sony Bravia 50\" 4K",
                            Price = 8995m,
                            QtyInStock = 12,
                            SubCategoryId = new Guid("00000301-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000031-0000-0000-0000-000000000000"),
                            Description = "4K TV med unikt Ambilight-system för immersiv upplevelse.",
                            Name = "Philips 43\" Ambilight",
                            Price = 6495m,
                            QtyInStock = 10,
                            SubCategoryId = new Guid("00000301-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000032-0000-0000-0000-000000000000"),
                            Description = "Branschledande brusreducering med 30h batteritid.",
                            Name = "Sony WH-1000XM5",
                            Price = 3495m,
                            QtyInStock = 20,
                            SubCategoryId = new Guid("00000302-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000033-0000-0000-0000-000000000000"),
                            Description = "Komfortabla over-ear med TriPort-akustik och ANC.",
                            Name = "Bose QuietComfort 45",
                            Price = 3295m,
                            QtyInStock = 15,
                            SubCategoryId = new Guid("00000302-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000034-0000-0000-0000-000000000000"),
                            Description = "Professionella kontorshörlurar med hybridANC och Teams-cert.",
                            Name = "Jabra Evolve2 55",
                            Price = 4195m,
                            QtyInStock = 10,
                            SubCategoryId = new Guid("00000302-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000035-0000-0000-0000-000000000000"),
                            Description = "Trådlösa over-ear med aktiv brusreducering och 30h batteri.",
                            Name = "Sennheiser HD 450BT",
                            Price = 1695m,
                            QtyInStock = 18,
                            SubCategoryId = new Guid("00000302-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000036-0000-0000-0000-000000000000"),
                            Description = "Vattentät Bluetooth-högtalare med 20h batteritid.",
                            Name = "JBL Charge 5",
                            Price = 1595m,
                            QtyInStock = 30,
                            SubCategoryId = new Guid("00000303-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000037-0000-0000-0000-000000000000"),
                            Description = "Smart WiFi-högtalare med stereopar-stöd och Trueplay.",
                            Name = "Sonos Era 100",
                            Price = 3295m,
                            QtyInStock = 14,
                            SubCategoryId = new Guid("00000303-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000038-0000-0000-0000-000000000000"),
                            Description = "Ikonisk design med kraftfullt ljud och Bluetooth 5.2.",
                            Name = "Marshall Stanmore III",
                            Price = 4495m,
                            QtyInStock = 8,
                            SubCategoryId = new Guid("00000303-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000039-0000-0000-0000-000000000000"),
                            Description = "Next-gen konsol med SSD, haptic feedback och 4K gaming.",
                            Name = "PlayStation 5",
                            Price = 6495m,
                            QtyInStock = 15,
                            SubCategoryId = new Guid("00000401-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000040-0000-0000-0000-000000000000"),
                            Description = "Kraftfullaste Xbox någonsin med 12 teraflops och Game Pass.",
                            Name = "Xbox Series X",
                            Price = 5995m,
                            QtyInStock = 13,
                            SubCategoryId = new Guid("00000401-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000041-0000-0000-0000-000000000000"),
                            Description = "Hybrid-konsol med 7-tums OLED-skärm och förbättrad ljud.",
                            Name = "Nintendo Switch OLED",
                            Price = 3595m,
                            QtyInStock = 22,
                            SubCategoryId = new Guid("00000401-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000042-0000-0000-0000-000000000000"),
                            Description = "Årets fotbollsspel med HyperMotion V-teknologi.",
                            Name = "EA Sports FC 25 PS5",
                            Price = 699m,
                            QtyInStock = 40,
                            SubCategoryId = new Guid("00000402-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000043-0000-0000-0000-000000000000"),
                            Description = "Upplev det magiska Hogwarts i ett öppet rollspel.",
                            Name = "Hogwarts Legacy Xbox",
                            Price = 549m,
                            QtyInStock = 35,
                            SubCategoryId = new Guid("00000402-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000044-0000-0000-0000-000000000000"),
                            Description = "Episkt äventyr i Hyrule för Nintendo Switch.",
                            Name = "Zelda: Tears of the Kingdom",
                            Price = 599m,
                            QtyInStock = 28,
                            SubCategoryId = new Guid("00000402-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000045-0000-0000-0000-000000000000"),
                            Description = "Öppen värld i Night City – nu med Phantom Liberty-expansion.",
                            Name = "Cyberpunk 2077 PC",
                            Price = 399m,
                            QtyInStock = 50,
                            SubCategoryId = new Guid("00000402-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000046-0000-0000-0000-000000000000"),
                            Description = "Sväng runt Manhattan som Peter Parker och Miles Morales.",
                            Name = "Spider-Man 2 PS5",
                            Price = 699m,
                            QtyInStock = 32,
                            SubCategoryId = new Guid("00000402-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000047-0000-0000-0000-000000000000"),
                            Description = "Mekaniskt tangentbord med Razer Green-switchar och RGB.",
                            Name = "Razer BlackWidow V3",
                            Price = 1295m,
                            QtyInStock = 18,
                            SubCategoryId = new Guid("00000403-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000048-0000-0000-0000-000000000000"),
                            Description = "Trådlös gaming-mus med LIGHTFORCE-switchar och 130h batteri.",
                            Name = "Logitech G502 X Plus",
                            Price = 1195m,
                            QtyInStock = 24,
                            SubCategoryId = new Guid("00000403-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000049-0000-0000-0000-000000000000"),
                            Description = "Trådlöst headset med 38h batteritid och ClearCast AI-mikrofon.",
                            Name = "SteelSeries Arctis Nova 7",
                            Price = 1995m,
                            QtyInStock = 16,
                            SubCategoryId = new Guid("00000403-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000050-0000-0000-0000-000000000000"),
                            Description = "Mekaniskt tangentbord med Cherry MX-switchar och USB-passthrough.",
                            Name = "Corsair K70 RGB Pro",
                            Price = 1495m,
                            QtyInStock = 12,
                            SubCategoryId = new Guid("00000403-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000051-0000-0000-0000-000000000000"),
                            Description = "Double Tap-gest, S9-chip och Always-On Retina-display.",
                            Name = "Apple Watch Series 9",
                            Price = 4995m,
                            QtyInStock = 20,
                            SubCategoryId = new Guid("00000501-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000052-0000-0000-0000-000000000000"),
                            Description = "Avancerad hälsomätning med BioActive Sensor och sleep coaching.",
                            Name = "Samsung Galaxy Watch 6",
                            Price = 3495m,
                            QtyInStock = 15,
                            SubCategoryId = new Guid("00000501-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000053-0000-0000-0000-000000000000"),
                            Description = "Premiumsmartwatch med AMOLED och avancerad sömn-analys.",
                            Name = "Garmin Venu 3",
                            Price = 4195m,
                            QtyInStock = 10,
                            SubCategoryId = new Guid("00000501-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000054-0000-0000-0000-000000000000"),
                            Description = "Elegant design med 14 dagars batteritid och GPS.",
                            Name = "Huawei Watch GT 4",
                            Price = 2695m,
                            QtyInStock = 13,
                            SubCategoryId = new Guid("00000501-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000055-0000-0000-0000-000000000000"),
                            Description = "Löparklocka med AMOLED, Training Readiness och HRV Status.",
                            Name = "Garmin Forerunner 265",
                            Price = 4495m,
                            QtyInStock = 12,
                            SubCategoryId = new Guid("00000502-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000056-0000-0000-0000-000000000000"),
                            Description = "Multisportklocka med EKG, optisk puls och SWR-sensor.",
                            Name = "Polar Vantage V3",
                            Price = 6495m,
                            QtyInStock = 7,
                            SubCategoryId = new Guid("00000502-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000057-0000-0000-0000-000000000000"),
                            Description = "Aktivitetsarmband med Google Maps, ECG och stress-hantering.",
                            Name = "Fitbit Charge 6",
                            Price = 1695m,
                            QtyInStock = 22,
                            SubCategoryId = new Guid("00000502-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000058-0000-0000-0000-000000000000"),
                            Description = "Adaptiv ljudavstängning, Personalized Spatial Audio och H2-chip.",
                            Name = "Apple AirPods Pro 2",
                            Price = 2995m,
                            QtyInStock = 25,
                            SubCategoryId = new Guid("00000503-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000059-0000-0000-0000-000000000000"),
                            Description = "Hi-Fi 24-bitars ljud med intelligent ANC och IPX7.",
                            Name = "Samsung Galaxy Buds2 Pro",
                            Price = 1995m,
                            QtyInStock = 20,
                            SubCategoryId = new Guid("00000503-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000060-0000-0000-0000-000000000000"),
                            Description = "Världens bästa ANC i ett kompakt format med 8h batteritid.",
                            Name = "Sony WF-1000XM5",
                            Price = 2795m,
                            QtyInStock = 18,
                            SubCategoryId = new Guid("00000503-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000061-0000-0000-0000-000000000000"),
                            Description = "Frontmatad tvättmaskin 9kg med EcoSilence Drive och WiFi.",
                            Name = "Bosch Serie 6 WGG14204S",
                            Price = 8995m,
                            QtyInStock = 6,
                            SubCategoryId = new Guid("00000601-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000062-0000-0000-0000-000000000000"),
                            Description = "EcoBubble-teknologi 9kg med AI Control och ångfunktion.",
                            Name = "Samsung WW90T684DLE",
                            Price = 7495m,
                            QtyInStock = 8,
                            SubCategoryId = new Guid("00000601-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000063-0000-0000-0000-000000000000"),
                            Description = "Tvättmaskin med SteamCare och UltraMix för skonsam tvätt.",
                            Name = "Electrolux PerfectCare 700",
                            Price = 6995m,
                            QtyInStock = 7,
                            SubCategoryId = new Guid("00000601-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000064-0000-0000-0000-000000000000"),
                            Description = "Fransk dörr-kylskåp med SpaceMax och Twin Cooling Plus.",
                            Name = "Samsung Side-by-Side RS68",
                            Price = 14995m,
                            QtyInStock = 4,
                            SubCategoryId = new Guid("00000602-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000065-0000-0000-0000-000000000000"),
                            Description = "NoFrost-kylskåp med FreshSense och VitaFresh-låda.",
                            Name = "Bosch KGN39AIAT",
                            Price = 9495m,
                            QtyInStock = 6,
                            SubCategoryId = new Guid("00000602-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000066-0000-0000-0000-000000000000"),
                            Description = "Total No Frost-kylskåp med DoorCooling+ och WiFi.",
                            Name = "LG GBB62PZGFN",
                            Price = 8495m,
                            QtyInStock = 7,
                            SubCategoryId = new Guid("00000602-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000067-0000-0000-0000-000000000000"),
                            Description = "Laser-detektering av damm, HEPA-filtrering och 60min drift.",
                            Name = "Dyson V15 Detect",
                            Price = 6995m,
                            QtyInStock = 10,
                            SubCategoryId = new Guid("00000603-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000068-0000-0000-0000-000000000000"),
                            Description = "Robotdammsugare med auto-tömning och moppfunktion.",
                            Name = "Roomba Combo j9+",
                            Price = 8995m,
                            QtyInStock = 8,
                            SubCategoryId = new Guid("00000603-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000069-0000-0000-0000-000000000000"),
                            Description = "Tredelad design, VARTA-batteri och 60min körtid.",
                            Name = "Miele Triflex HX2 Pro",
                            Price = 5995m,
                            QtyInStock = 9,
                            SubCategoryId = new Guid("00000603-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000070-0000-0000-0000-000000000000"),
                            Description = "3 smarta glödlampor med Hue Bridge och 16M färger.",
                            Name = "Philips Hue Starterkit E27",
                            Price = 1295m,
                            QtyInStock = 25,
                            SubCategoryId = new Guid("00000701-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000071-0000-0000-0000-000000000000"),
                            Description = "Prisvärt smart belysningssystem med dimmer och gateway.",
                            Name = "IKEA TRÅDFRI Startpaket",
                            Price = 599m,
                            QtyInStock = 35,
                            SubCategoryId = new Guid("00000701-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000072-0000-0000-0000-000000000000"),
                            Description = "Modulära LED-linjer med musik-reaktivitet och Touch Control.",
                            Name = "Nanoleaf Lines Starter",
                            Price = 1995m,
                            QtyInStock = 15,
                            SubCategoryId = new Guid("00000701-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000073-0000-0000-0000-000000000000"),
                            Description = "RGBIC neontejp med app-kontroll och musik-synkronisering.",
                            Name = "Govee Neon Rope Light 3m",
                            Price = 799m,
                            QtyInStock = 20,
                            SubCategoryId = new Guid("00000701-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000074-0000-0000-0000-000000000000"),
                            Description = "3D Motion Detection, Bird's Eye View och 1536p HD-video.",
                            Name = "Ring Video Doorbell Pro 2",
                            Price = 2995m,
                            QtyInStock = 12,
                            SubCategoryId = new Guid("00000702-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000075-0000-0000-0000-000000000000"),
                            Description = "2K HDR, färg-nattseende och 6 månaders batteritid.",
                            Name = "Arlo Pro 5S utomhuskamera",
                            Price = 2495m,
                            QtyInStock = 10,
                            SubCategoryId = new Guid("00000702-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000076-0000-0000-0000-000000000000"),
                            Description = "Modulärt larmsystem med inomhuskamera och rörelsedetektering.",
                            Name = "Netatmo Smart Alarm System",
                            Price = 3495m,
                            QtyInStock = 7,
                            SubCategoryId = new Guid("00000702-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000077-0000-0000-0000-000000000000"),
                            Description = "Kompakt smart högtalare med Alexa och förbättrat ljud.",
                            Name = "Amazon Echo Dot 5th gen",
                            Price = 499m,
                            QtyInStock = 40,
                            SubCategoryId = new Guid("00000703-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000078-0000-0000-0000-000000000000"),
                            Description = "Smart skärm med Google Assistant och sömnspårning.",
                            Name = "Google Nest Hub 2nd gen",
                            Price = 999m,
                            QtyInStock = 25,
                            SubCategoryId = new Guid("00000703-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000079-0000-0000-0000-000000000000"),
                            Description = "360-graders ljud, Siri och smarthemshub i ett kompakt format.",
                            Name = "Apple HomePod mini",
                            Price = 1095m,
                            QtyInStock = 20,
                            SubCategoryId = new Guid("00000703-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000080-0000-0000-0000-000000000000"),
                            Description = "WiFi 6E Mesh-system med tri-band och 10Gbps WAN/LAN.",
                            Name = "ASUS ZenWiFi Pro ET12",
                            Price = 8995m,
                            QtyInStock = 6,
                            SubCategoryId = new Guid("00000801-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000081-0000-0000-0000-000000000000"),
                            Description = "WiFi 6E Mesh 3-pack med EasyMesh och föräldrakontroll.",
                            Name = "TP-Link Deco XE75 Pro",
                            Price = 4995m,
                            QtyInStock = 9,
                            SubCategoryId = new Guid("00000801-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000082-0000-0000-0000-000000000000"),
                            Description = "Amazon Mesh-system med Zigbee-hubb och enkel app-setup.",
                            Name = "Eero Pro 6E 3-pack",
                            Price = 5495m,
                            QtyInStock = 8,
                            SubCategoryId = new Guid("00000801-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000083-0000-0000-0000-000000000000"),
                            Description = "WiFi 6 Mesh med 6Gbps total bandbredd och 6 enheter.",
                            Name = "Netgear Orbi RBK863S",
                            Price = 6995m,
                            QtyInStock = 5,
                            SubCategoryId = new Guid("00000801-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000084-0000-0000-0000-000000000000"),
                            Description = "Kompakt 2-bays NAS med DiskStation Manager och RAID.",
                            Name = "Synology DS223",
                            Price = 3295m,
                            QtyInStock = 8,
                            SubCategoryId = new Guid("00000802-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000085-0000-0000-0000-000000000000"),
                            Description = "2-bay NAS med 8TB och automatisk moln-backup.",
                            Name = "WD My Cloud EX2 Ultra",
                            Price = 4495m,
                            QtyInStock = 6,
                            SubCategoryId = new Guid("00000802-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000086-0000-0000-0000-000000000000"),
                            Description = "Robust portabel SSD med USB 3.2 Gen2 och IP65-klassning.",
                            Name = "Samsung T7 Shield 2TB",
                            Price = 1195m,
                            QtyInStock = 20,
                            SubCategoryId = new Guid("00000802-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000087-0000-0000-0000-000000000000"),
                            Description = "Portabel NVMe SSD med 2000MB/s och drop-skydd.",
                            Name = "SanDisk Extreme Pro 4TB",
                            Price = 1895m,
                            QtyInStock = 15,
                            SubCategoryId = new Guid("00000802-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000088-0000-0000-0000-000000000000"),
                            Description = "18 portar inkl. 2x Thunderbolt 4, 2x USB-A och 2.5GbE.",
                            Name = "CalDigit TS4 Thunderbolt 4",
                            Price = 4295m,
                            QtyInStock = 7,
                            SubCategoryId = new Guid("00000803-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000089-0000-0000-0000-000000000000"),
                            Description = "13-i-1 dockningsstation med 85W laddning och dual 4K.",
                            Name = "Anker 575 USB-C Docking",
                            Price = 1995m,
                            QtyInStock = 12,
                            SubCategoryId = new Guid("00000803-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000090-0000-0000-0000-000000000000"),
                            Description = "Kompakt hub med HDMI 4K, SD-kortläsare och 100W PD.",
                            Name = "Belkin Connect USB-C 11-i-1",
                            Price = 1295m,
                            QtyInStock = 18,
                            SubCategoryId = new Guid("00000803-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000091-0000-0000-0000-000000000000"),
                            Description = "Kraftfull pro-surfplatta med M2-chip, Liquid Retina XDR och 5G.",
                            Name = "iPad Pro 12.9\" M2",
                            Price = 13995m,
                            QtyInStock = 8,
                            SubCategoryId = new Guid("00000202-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000092-0000-0000-0000-000000000000"),
                            Description = "Ultralätt trådlös gaming-mus med HERO 25K-sensor.",
                            Name = "Logitech G Pro X Superlight",
                            Price = 1595m,
                            QtyInStock = 14,
                            SubCategoryId = new Guid("00000403-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000093-0000-0000-0000-000000000000"),
                            Description = "USB-C 4K-skärm optimerad för Mac med 96W laddning.",
                            Name = "LG 27\" 4K UltraFine",
                            Price = 6495m,
                            QtyInStock = 8,
                            SubCategoryId = new Guid("00000103-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000094-0000-0000-0000-000000000000"),
                            Description = "Stor portabel högtalare med PartyMode och 20h batteritid.",
                            Name = "Bose SoundLink Max",
                            Price = 4495m,
                            QtyInStock = 10,
                            SubCategoryId = new Guid("00000303-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000095-0000-0000-0000-000000000000"),
                            Description = "5.3K video, HyperSmooth 6.0 och vattentät till 10m.",
                            Name = "GoPro Hero 12 Black",
                            Price = 4995m,
                            QtyInStock = 12,
                            SubCategoryId = new Guid("00000104-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000096-0000-0000-0000-000000000000"),
                            Description = "Robotdammsugare med laser-navigering och moppfunktion.",
                            Name = "Xiaomi Robot Vacuum S20+",
                            Price = 4495m,
                            QtyInStock = 10,
                            SubCategoryId = new Guid("00000603-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000097-0000-0000-0000-000000000000"),
                            Description = "Hybridklocka med EKG, SpO2 och 30 dagars batteritid.",
                            Name = "Withings ScanWatch 2",
                            Price = 3495m,
                            QtyInStock = 9,
                            SubCategoryId = new Guid("00000501-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000098-0000-0000-0000-000000000000"),
                            Description = "Capture card med 4K60 HDR10 och VRR-stöd.",
                            Name = "Elgato 4K60 Pro MK.2",
                            Price = 2495m,
                            QtyInStock = 8,
                            SubCategoryId = new Guid("00000403-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000099-0000-0000-0000-000000000000"),
                            Description = "Utomhuskamera 4MP med ColorPro Night Vision och AI-detektion.",
                            Name = "TP-Link Tapo C320WS",
                            Price = 595m,
                            QtyInStock = 25,
                            SubCategoryId = new Guid("00000702-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000100-0000-0000-0000-000000000000"),
                            Description = "PCIe 4.0 SSD med 7000MB/s läshastighet och aluminium heatsink.",
                            Name = "Corsair MP600 Pro 2TB NVMe",
                            Price = 2195m,
                            QtyInStock = 14,
                            SubCategoryId = new Guid("00000802-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Entities.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000000"),
                            Name = "Datorer & Tillbehör"
                        },
                        new
                        {
                            Id = new Guid("00000002-0000-0000-0000-000000000000"),
                            Name = "Telefoner & Surfplattor"
                        },
                        new
                        {
                            Id = new Guid("00000003-0000-0000-0000-000000000000"),
                            Name = "TV & Ljud"
                        },
                        new
                        {
                            Id = new Guid("00000004-0000-0000-0000-000000000000"),
                            Name = "Gaming"
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000000"),
                            Name = "Wearables"
                        },
                        new
                        {
                            Id = new Guid("00000006-0000-0000-0000-000000000000"),
                            Name = "Vitvaror"
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000000"),
                            Name = "Smarta hem & IoT"
                        },
                        new
                        {
                            Id = new Guid("00000008-0000-0000-0000-000000000000"),
                            Name = "Nätverk & Lagring"
                        });
                });

            modelBuilder.Entity("Entities.ProductOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductOrders");
                });

            modelBuilder.Entity("Entities.ProductSubCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ParentCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("ProductSubCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000101-0000-0000-0000-000000000000"),
                            Name = "Laptops",
                            ParentCategoryId = new Guid("00000001-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000102-0000-0000-0000-000000000000"),
                            Name = "Stationära datorer",
                            ParentCategoryId = new Guid("00000001-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000103-0000-0000-0000-000000000000"),
                            Name = "Datorskärmar",
                            ParentCategoryId = new Guid("00000001-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000104-0000-0000-0000-000000000000"),
                            Name = "Datortillbehör",
                            ParentCategoryId = new Guid("00000001-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000201-0000-0000-0000-000000000000"),
                            Name = "Smartphones",
                            ParentCategoryId = new Guid("00000002-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000202-0000-0000-0000-000000000000"),
                            Name = "Surfplattor",
                            ParentCategoryId = new Guid("00000002-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000203-0000-0000-0000-000000000000"),
                            Name = "Mobilskal & Tillbehör",
                            ParentCategoryId = new Guid("00000002-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000301-0000-0000-0000-000000000000"),
                            Name = "TV-apparater",
                            ParentCategoryId = new Guid("00000003-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000302-0000-0000-0000-000000000000"),
                            Name = "Hörlurar",
                            ParentCategoryId = new Guid("00000003-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000303-0000-0000-0000-000000000000"),
                            Name = "Högtalare",
                            ParentCategoryId = new Guid("00000003-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000401-0000-0000-0000-000000000000"),
                            Name = "Spelkonsoler",
                            ParentCategoryId = new Guid("00000004-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000402-0000-0000-0000-000000000000"),
                            Name = "Spel",
                            ParentCategoryId = new Guid("00000004-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000403-0000-0000-0000-000000000000"),
                            Name = "Gaming-tillbehör",
                            ParentCategoryId = new Guid("00000004-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000501-0000-0000-0000-000000000000"),
                            Name = "Smartwatches",
                            ParentCategoryId = new Guid("00000005-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000502-0000-0000-0000-000000000000"),
                            Name = "Träningsklockor",
                            ParentCategoryId = new Guid("00000005-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000503-0000-0000-0000-000000000000"),
                            Name = "Trådlösa earbuds",
                            ParentCategoryId = new Guid("00000005-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000601-0000-0000-0000-000000000000"),
                            Name = "Tvättmaskiner",
                            ParentCategoryId = new Guid("00000006-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000602-0000-0000-0000-000000000000"),
                            Name = "Kylskåp & Frysar",
                            ParentCategoryId = new Guid("00000006-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000603-0000-0000-0000-000000000000"),
                            Name = "Dammsugare",
                            ParentCategoryId = new Guid("00000006-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000701-0000-0000-0000-000000000000"),
                            Name = "Smart belysning",
                            ParentCategoryId = new Guid("00000007-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000702-0000-0000-0000-000000000000"),
                            Name = "Säkerhet & Kameror",
                            ParentCategoryId = new Guid("00000007-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000703-0000-0000-0000-000000000000"),
                            Name = "Smarta assistenter",
                            ParentCategoryId = new Guid("00000007-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000801-0000-0000-0000-000000000000"),
                            Name = "Routrar & Mesh",
                            ParentCategoryId = new Guid("00000008-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000802-0000-0000-0000-000000000000"),
                            Name = "NAS & Extern lagring",
                            ParentCategoryId = new Guid("00000008-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00000803-0000-0000-0000-000000000000"),
                            Name = "USB-hubbar & Dockningar",
                            ParentCategoryId = new Guid("00000008-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Entities.Shipping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TypeOfShipping")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Shippings");
                });

            modelBuilder.Entity("Entities.CustomerContactInfo", b =>
                {
                    b.HasOne("Entities.Customer", "Customer")
                        .WithOne("CustomerContactInfo")
                        .HasForeignKey("Entities.CustomerContactInfo", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Entities.Offer", b =>
                {
                    b.HasOne("Entities.Product", "Product")
                        .WithOne("Offer")
                        .HasForeignKey("Entities.Offer", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Entities.Order", b =>
                {
                    b.HasOne("Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.PaymentMethod", "PaymentMethod")
                        .WithMany("Orders")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Shipping", "Shipping")
                        .WithMany()
                        .HasForeignKey("ShippingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("PaymentMethod");

                    b.Navigation("Shipping");
                });

            modelBuilder.Entity("Entities.Product", b =>
                {
                    b.HasOne("Entities.ProductSubCategory", "SubCategory")
                        .WithMany("Products")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("Entities.ProductOrder", b =>
                {
                    b.HasOne("Entities.Order", "Order")
                        .WithMany("ProductOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Product", "Product")
                        .WithMany("ProductOrders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Entities.ProductSubCategory", b =>
                {
                    b.HasOne("Entities.ProductCategory", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Entities.Customer", b =>
                {
                    b.Navigation("CustomerContactInfo");
                });

            modelBuilder.Entity("Entities.Order", b =>
                {
                    b.Navigation("ProductOrders");
                });

            modelBuilder.Entity("Entities.PaymentMethod", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Entities.Product", b =>
                {
                    b.Navigation("Offer");

                    b.Navigation("ProductOrders");
                });

            modelBuilder.Entity("Entities.ProductCategory", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Entities.ProductSubCategory", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
